In [ ]:
Matrizes

In [2]:
import numpy as np
matriz = np.array([[1, 2, 3], 
                   [4, 5, 6]])

In [3]:
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
matriz.shape

(2, 3)

In [6]:
matriz[0]

array([1, 2, 3])

In [7]:
matriz[1]

array([4, 5, 6])

In [9]:
matriz[3]

IndexError: index 3 is out of bounds for axis 0 with size 2

In [10]:
matriz[0][2]

3

In [11]:
matriz[1][2]

6

In [17]:
matriz.shape[0]

2

In [19]:
for linha in range(matriz.shape[0]):
    print(matriz[linha])
    for coluna in range(matriz.shape[1]):
        print(matriz[linha][coluna])

[1 2 3]
1
2
3
[4 5 6]
4
5
6
